module.exports = {
    parser: 'vue-eslint-parser',
    env: {
        browser: true,
    },
    overrides: [
        {
            files: ['*.vue'],
            plugins: ['vue'],
            extends: ['plugin:vue/vue3-recommended'],
            rules: {
                'vue/max-attributes-per-line': 0,
                'vue/html-indent': ['error', 4],
                'vue/no-v-html': 0,
                'vue/no-template-shadow': 'error',
                'vue/multi-word-component-names': 0,
                'vue/attributes-order': 'error',
                'vue/order-in-components': 'error',
                // https://eslint.vuejs.org/rules/no-v-for-template-key-on-child.html
                'vue/no-v-for-template-key': 'off',
                'vue/attribute-hyphenation': 'error',
                'vue/prop-name-casing': 'off',
                'vue/no-static-inline-styles': 'error',
                'vue/block-tag-newline': 'error',
                'vue/define-macros-order': 'error',
                'vue/component-tags-order': ['error', { order: ['route', ['template', 'script'], 'style'] }],
                'vue/component-api-style': 'error',
                'vue/component-name-in-template-casing': 'error',
                'vue/custom-event-name-casing': ['error', 'kebab-case'],
                'vue/no-multiple-objects-in-class': 'error',
                'vue/no-useless-v-bind': 'error',
                'vue/no-useless-mustaches': 'error',
                'vue/no-unused-properties': ['error', { groups: ['setup'] }],
                'vue/no-v-text': 'error',
                'vue/padding-line-between-blocks': 'error',
                'vue/prefer-prop-type-boolean-first': 'error',
                'vue/prefer-true-attribute-shorthand': 'error',
                'vue/prefer-separate-static-class': 'error',
                'vue/define-props-declaration': 'error',
                'vue/define-emits-declaration': 'error',
                'vue/require-macro-variable-name': 'error',
                'vue/no-duplicate-attr-inheritance': 'error',
            },
        },
    ],
};
